services:
  db:
    image: postgres:15
    container_name: booking_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: booking_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run uvicorn src.one_star_booking.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: